services:
  proyecto-db:
    image: postgres:17.0
    container_name: proyecto-db
    restart: always
    environment:
      POSTGRES_DB: proyectoFinal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    networks:
      - proyecto-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./crear_base_datos_gastos_familiares.sql:/docker-entrypoint-initdb.d/crear_base_datos_gastos_familiares.sql

  backend-proyect:
    build:
      context: .
    container_name: backend-proyect
    restart: always
    depends_on:
      - proyecto-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://proyecto-db:5432/proyectoFinal
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8091:8091"
    networks:
      - proyecto-network

networks:
  proyecto-network:

volumes:
  db_data:
