
DROP TABLE IF EXISTS vocalistas;
DROP TABLE IF EXISTS solistas;
DROP TABLE IF EXISTS integrantes;
DROP TABLE IF EXISTS batallas;
DROP TABLE IF EXISTS bandas;
DROP TABLE IF EXISTS rondas;
DROP TABLE IF EXISTS localidades;