###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "hrisi",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristiyantg10@gmail.com",
    "password": "Hrisi231104!",
    "telefono":"722 591 444"
}
###
###
POST http://localhost:8091/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDcxNjk2NTksImV4cCI6MTc0NzIwNTY1OX0.D6halfDBcrJZujt2C4-PMnr8mUKqc3ktHVPPouJVNUg
Content-Type: application/json

###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "andres",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristiyantg3@gmail.com",
    "password": "Hrisi231104!",
    "telefono":"678 591 444"

}


###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "andres2",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristiyantg6@gmail.com",
    "password": "Hrisi231104!",
    "telefono":"678 591 444"

}
###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "andres8",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristias@gmail.com",
    "password": "Hrisi231104!",
    "telefono":"678 591 444"

}
###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "anes3",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristiy@gmail.com",
    "password": "Hrisi231104!",
    "telefono":"678 591 444"

}
###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "and3",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristyantg5@gmail.com",
    "password": "Hrisi231104!",
    "telefono":"678 591 444"

}
###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "andro3",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristi@gmail.com",
    "password": "Hrisi231104!",
    "telefono":"678 591 444"

}
###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "andri3",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristiyan@gmail.com",
    "password": "Hrisi231104!",
    "telefono":"678 591 444"

}

###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "andres3",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristiyantg5@gmail.com",
    "password": "Hrisi231104!",
    "telefono":"678 591 444"

}
###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "sofia2",
    "nombre": "sofia\nTrayanova",
    "email": "sofiatg@gmail.com",
    "password": "Sofia230512!",
    "telefono":"888 888 888"
}

###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "sofia",
    "nombre": "sofia\nTrayanova",
    "email": "sofiatg2@gmail.com",
    "password": "Sofia230512!",
    "telefono":"888 888 888"
}

###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "sofia4",
    "nombre": "sofia\nTrayanova",
    "email": "sofiat4g@gmail.com",
    "password": "Sofia230512!",
    "telefono":"888 888 888"
}
###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "sofia3",
    "nombre": "sofia\nTrayanova",
    "email": "sofiat3g@gmail.com",
    "password": "Sofia230512!",
    "telefono":"888 888 888"
}
###
## login ok PERMISOS 
POST http://localhost:8091/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "andri3",
    "password": "Hrisi231104!"
}
###
## login ok PERMISOS ROLE_USER
POST http://localhost:8091/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "sofia2",
    "password": "Sofia230512!"
}
###
## login ok PERMISOS ROLE_USER
POST http://localhost:8091/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "andres2",
    "password": "Hrisi231104!"
}
###
## Crear gasto (asegúrate de usar enums válidos en tipoGasto y subtipo)
POST http://localhost:8091/api/gastos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyaTMiLCJpYXQiOjE3NDgyNzUxMzUsImV4cCI6MTc0ODMxMTEzNX0.Ht8szEdEyIyP0XEFydfAVo9ClTPf5Y1SVsGNjuHgi5M

{
  "usuario": { "id": 1 },
  "grupo": { "id": 1 },
  "tipoGasto": "LUJO",
  "subtipo": "ESPECTACULOS",
  "cantidad": "15,50",
  "fecha": "2025-04-06"
}
###
## Obtener gasto por ID
GET http://localhost:8091/api/gastos/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDUyNTc1MTgsImV4cCI6MTc0NTI5MzUxOH0.68KBlr8CwrklAz-6ftojIvWWYMYrv5BSYQj53XZ216A

###
## Actualizar gasto
PUT http://localhost:8091/api/gastos/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyNzUzNTAsImV4cCI6MTc0NjMxMTM1MH0.qm4iOC3oo0SGPVG9ZFa2frhPkDubhWyHo0TvG7aOmqM

{
  "usuario": { "id": 1 },
  "grupo": { "id": 1 },
  "tipoGasto": "SUPERVIVENCIA",
  "subtipo": "COMIDA",
  "cantidad": 75.00,
  "fecha": "2025-04-07"
}
###
## Eliminar gasto
DELETE http://localhost:8091/api/gastos/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDUzNDI2NTcsImV4cCI6MTc0NTM3ODY1N30.rVvwNwyObe9AjRAtI0XQbxgcGdvigEZalVD4TdDmw4g

###
## Actualizar gasto con id 3
PUT http://localhost:8091/api/gastos/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyODY5MTAsImV4cCI6MTc0NjMyMjkxMH0.wd-Ah-9kkgvFEpDsibVIcpAX8Ef5tCqm_FWE0kT4cnI

{
  "tipoGasto": "LUJO",
  "subtipo": "VIAJES",
  "cantidad": "123,45",
  "fecha": "2025-05-02"
}


###
## Crear grupo familiar (el usuario será el administrador automáticamente si así lo configuraste)
POST http://localhost:8091/api/grupos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxOTU1NTIsImV4cCI6MTc0ODIzMTU1Mn0.tSS_0-k9DUHrSrOI3LqM_1mu9VfmnNJsRNn-ln2IWxc

{
  "nombre": "Familia Trayanov"
}
###
## Obtener grupo por ID
GET http://localhost:8091/api/grupos/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxMTY2NTIsImV4cCI6MTc0ODE1MjY1Mn0.iWtiL8ZwT2cARG-BZuJYR5gbC-SZaMpLNKynE8BgskM





###
### Obtener todos los mensajes
GET http://localhost:8091/api/mensajes HTTP/1.1
Authorization: Bearer [TU_TOKEN_AQUI]

###
### Obtener un mensaje por ID
GET http://localhost:8091/api/mensajes/1 HTTP/1.1
Authorization: Bearer [TU_TOKEN_AQUI]

###
### Obtener mensajes por receptor
GET http://localhost:8091/api/mensajes/receptor/1 HTTP/1.1
Authorization: Bearer [TU_TOKEN_AQUI]

###
### Obtener mensajes por grupo
GET http://localhost:8091/api/mensajes/grupo/1 HTTP/1.1
Authorization: Bearer [TU_TOKEN_AQUI]

###
### Crear mensaje
POST http://localhost:8091/api/mensajes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDY0NzgzMTQsImV4cCI6MTc0NjUxNDMxNH0.Sgo9-V2JYBsStYSUs1LPYjpO22oxTCOWyME0vtRAoJg

{
  "emisorId": 1,
  "receptorId": 2,
  "grupoId": 3,
  "contenido": "¡Hola!"
}

###
### Actualizar un mensaje
PUT http://localhost:8091/api/mensajes/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer [TU_TOKEN_AQUI]

{
"emisor": {
"id": 1
},
"receptor": {
"id": 2
},
"grupo": {
"id": 1
},
"contenido": "¡Hola de nuevo! Mensaje actualizado",
"fecha": "2025-05-03T17:00:00",
"tipo": "TEXTO"
}

###
### Eliminar un mensaje
DELETE http://localhost:8091/api/mensajes/1 HTTP/1.1
Authorization: Bearer [TU_TOKEN_AQUI]







###
## Actualizar grupo (solo el administrador puede)
PUT http://localhost:8091/api/grupos/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDUzNDI2NTcsImV4cCI6MTc0NTM3ODY1N30.rVvwNwyObe9AjRAtI0XQbxgcGdvigEZalVD4TdDmw4g

{
  "nombre": "Familia Trayanov Actualizado"
}
###
## Eliminar grupo
DELETE http://localhost:8091/api/grupos/6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyZXMiLCJpYXQiOjE3NDgxMTE3MTAsImV4cCI6MTc0ODE0NzcxMH0.qoHTDIFD3nL6GApiWTesFdMV1-utsJHj0A4hIi7fNEI


###
## Sumar gastos de luju espectaculos
GET http://localhost:8091/api/gastos/suma-gastos?tipoGasto=LUJO&subtipo=ESPECTACULOS
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyODQyMjIsImV4cCI6MTc0NjMyMDIyMn0.cBdXM4tbrULQlOZSoyiF9-OqvL0vJmbGV3hiTP_JM5E

###
## sumar gastos de tipo lujo
GET http://localhost:8091/api/gastos/suma-gastos?tipoGasto=LUJO
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyODQyMjIsImV4cCI6MTc0NjMyMDIyMn0.cBdXM4tbrULQlOZSoyiF9-OqvL0vJmbGV3hiTP_JM5E


###
### Crear una invitación para un usuario con nickname "sofia2" al grupo 1
POST http://localhost:8091/api/invitaciones HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxOTY3OTQsImV4cCI6MTc0ODIzMjc5NH0.qp5ITzyfdrvn15GxAMkXIigBozp7nlPcvMSCA42v2XE

{
  "nickname": "andri3",
  "grupoId": 1
}

###
### Obtener invitaciones del grupo con ID 1
GET http://localhost:8091/api/invitaciones/grupo/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDU0Mzg1ODAsImV4cCI6MTc0NTQ3NDU4MH0.RKGTRyu1PMudULyTh0hPA4RaxeqfWuoABXhuPgi5fQ8

###
### Obtener invitaciones paginadas
GET http://localhost:8091/api/invitaciones HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDc5MzgyMDUsImV4cCI6MTc0Nzk3NDIwNX0.oHrRN8yY93uvKgdOn7r3QLPcOVMzOcmMcicpis_sJT0

###
### Marcar invitación con ID 1 como aceptada
PUT http://localhost:8091/api/invitaciones/1/estado?nuevoEstado=ACEPTADA HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyaTMiLCJpYXQiOjE3NDgxOTY4MjMsImV4cCI6MTc0ODIzMjgyM30.rYFA1B3meRXgtbThH9uKdU_ml-xvyBkw-KMyPlHF6es

###
### Obtener todas las invitaciones dirigidas al usuario autenticado

GET http://localhost:8091/api/invitaciones/usuario HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDU5NTE4OTUsImV4cCI6MTc0NTk4Nzg5NX0.w0qqvfChYLeCoT-pqvhfEe-MZOh8GBfAS01nNZgSGUA


###
### Asignar el rol de padre a un usuario del grupo (solo el admin puede hacerlo)Marcar invitación con ID 5 como aceptada
PUT http://localhost:8091/api/grupos/asignar-rol?nicknameDestino=andres&rol=PADRE HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxMTM4NjIsImV4cCI6MTc0ODE0OTg2Mn0.MoO4w2PUHOvM7NF16gw0JwkUdMwJp3xjW7ecxSOW97Y


###
### Quitar rol padre
PUT http://localhost:8091/api/grupos/limpiar-roles?nicknameDestino=andres HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxMTM4NjIsImV4cCI6MTc0ODE0OTg2Mn0.MoO4w2PUHOvM7NF16gw0JwkUdMwJp3xjW7ecxSOW97Y

###
### ARechazar una invitacion
PUT http://localhost:8091/api/invitaciones/1/estado?nuevoEstado=RECHAZADA HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDU5NTE4OTUsImV4cCI6MTc0NTk4Nzg5NX0.w0qqvfChYLeCoT-pqvhfEe-MZOh8GBfAS01nNZgSGUA

###
### Obtener invitaciones del usuario auth con filtros
GET http://localhost:8091/api/invitaciones/filter?filter=nicknameDestino:CONTIENE:sofia2&filter=grupo.nombre:CONTIENE:Familiapage=0&size=10&sort=fechaEnvio,desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDc5NDA5MTUsImV4cCI6MTc0Nzk3NjkxNX0.7BOg6HMeaIgnfam6Tfq86dleJCfmfOWv3Xw9UhFLsvA

###
### Abandonar el grupo familiar actual (el usuario abandona su grupo)
DELETE http://localhost:8091/api/grupos/abandonar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDU5NTM4NDQsImV4cCI6MTc0NTk4OTg0NH0.X_1RrolfqQI-IGrZ0VbiIPvZh_siCR4RtJPsVYXhZgg

###
### Obtener usuarios
GET http://localhost:8091/api/grupos/2/usuarios HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxMTYyNDEsImV4cCI6MTc0ODE1MjI0MX0.OKYZDF5r28Z4YgDKaPgC13y_v6506mo13MSuDPQOLBg
###
### Expulsar al usuario  del grupo familiar con ID 1
PUT http://localhost:8091/api/grupos/1/eliminar-usuario/sofia2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDgwMjMwMzQsImV4cCI6MTc0ODA1OTAzNH0.mdyfGhS-rucjrMF4KJN0Qz6xrmMtHFG8RV-JwXyCTuY
Content-Type: application/json
###
### Actualizar mis propios datos (nickname viejo en la URL)
PUT http://localhost:8091/api/usuarios/hrisi5/actualizar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTUiLCJpYXQiOjE3NDc0MTc0MjAsImV4cCI6MTc0NzQ1MzQyMH0.8XHIfROmhBdn3HX9SvxlZu6ySRC7pjNJ5UKrbw9gR1M
Content-Type: application/json

{
  "nombre":   "Andrés González",
  "nickname": "hrisi4",
  "email":    "administrador@gmail.com",
  "telefono": "+34123456789"
}
###
### Obtener perfil del usuario autenticado
GET http://localhost:8091/api/usuarios/perfil HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyZXMiLCJpYXQiOjE3NDgxMTMwODUsImV4cCI6MTc0ODE0OTA4NX0.qv7BfwgXsza7yGeBUPRnt3ARkYjMKkMrim5-vZ8grD8



### Obtener todos los usuarios (paginados básicos)
###
GET http://localhost:8091/api/usuarios/usuarios?page=0&size=3&sort=id,desc&sort=id,desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxODE2MDAsImV4cCI6MTc0ODIxNzYwMH0.U1Ev0QNUuAdQTy0lprajCBG12kPDoJ6wC_rhdN4m6Ys

###Obtener todos los usuarios paginados
###
GET http://localhost:8091/api/usuarios/v1/usuarios?page=0&size=3&sortField=id&sortDirection=asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDY1NTk3MzMsImV4cCI6MTc0NjU5NTczM30.j1fOFjsU6smoXbRmiSldM6LsiEUibzMOfBMgj0TOUJs

###Obtener los usuarios mediante busqueda
###
POST http://localhost:8091/api/usuarios/v1/usuarios/x HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDY1NTgzNzIsImV4cCI6MTc0NjU5NDM3Mn0.0dZH2bs9V_cG8rxTL0IB38bDyoHt63HvnoYTbYMBDIk

{
  "pagina": 0,
  "size": 3,
  "sort": ["id,asc"],
  "listaFiltros": [
    {
      "campo": "nombre",
      "operador": "contiene",
      "valor": "hris"
    }
  ]
}
### Obtener usuarios con filtros
###
GET http://localhost:8091/api/usuarios/filter?filter=nickname:IGUAL:hrisi&page=0&size=10&sort=id,asc&sort=id,asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxODgyNzUsImV4cCI6MTc0ODIyNDI3NX0.jRP4ELuTQ4apu_Kx22lWlJHqVXYfXad5yCWa3wnjp4Y

### Obtener todos los usuarios paginados
### 
GET http://localhost:8091/api/usuarios/usuarios?page=0&size=10&sort=id,asc&sort=id,asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDY2NDA4NDksImV4cCI6MTc0NjY3Njg0OX0.o4N04Wp7ElXIao9bPGmFjvHNCbmpVttcEYeO-mOUjKA

### Obtener usuarios con filtros
###
POST http://localhost:8091/api/usuarios/filter HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDY2NDQ5MTIsImV4cCI6MTc0NjY4MDkxMn0.jrnvjcgLpfMPEA_5g598svk2l8VwWsbIHe-2iEynIGU

{
  "listaFiltros": [
    {
      "atributo": "nombre",
      "operacion": "CONTIENE",
      "valor": "hris"
    }
  ],
  "page": 0,
  "size": 10,
  "sort": ["id,asc"]
}

### Obtener gastos con filtros se filtra por usuario tipo y subtipo
###
GET http://localhost:8091/api/gastos/filter?nickname=sofia2&filter=tipoGasto:CONTIENE:LUJO&filter=subtipo:IGUAL:BANKINTER&page=0&size=10&sort=fecha,desc&sort=fecha,desc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgyNzU5ODIsImV4cCI6MTc0ODMxMTk4Mn0.Qlni_Fcx2xOFVsc9Vya5OfHoUajGEqM9R8uqaViwPO8

###
###Obtener todos los gastos paginados
GET http://localhost:8091/api/gastos/page?page=0&size=5&sort=fecha,desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgyNzU5ODIsImV4cCI6MTc0ODMxMTk4Mn0.Qlni_Fcx2xOFVsc9Vya5OfHoUajGEqM9R8uqaViwPO8

###
###Obtener gastos filtrados por tipo y subtipo
GET http://localhost:8091/api/gastos/page?page=0&size=20&sort=fecha,asc&tipoGasto=LUJO&subtipo=ESPECTACULOS HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDY2NDgzMzgsImV4cCI6MTc0NjY4NDMzOH0.flJ_dLmBVAvvH6n2fYffeAkS6tV2dF7Nrq_eFw32jW8



### 
### Filtrar gastos por nickname del usuario y el nombre del grupo
GET http://localhost:8091/api/gastos/filter?nicknameDestino:IGUAL:sofia2&filter=grupoNombre:IGUAL:Fam&page=0&size=10&sort=fecha,desc&sort=fecha,desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDc2OTAzMjgsImV4cCI6MTc0NzcyNjMyOH0.CprFVHnfSM4ZDBzHpt0Y2RoGRaFdVWIlneMp-tTvcAc


### 
### Crear un ingreso
POST http://localhost:8091/api/ingresos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyaTMiLCJpYXQiOjE3NDgxOTY4MjMsImV4cCI6MTc0ODIzMjgyM30.rYFA1B3meRXgtbThH9uKdU_ml-xvyBkw-KMyPlHF6es
Content-Type: application/json

{
  "cantidad": "110,56"
}


### 
### Listar ingresos del grupo del usuario 
GET http://localhost:8091/api/ingresos?page=0&size=10&sort=id,asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyaTMiLCJpYXQiOjE3NDgxOTY4MjMsImV4cCI6MTc0ODIzMjgyM30.rYFA1B3meRXgtbThH9uKdU_ml-xvyBkw-KMyPlHF6es

### 
### Actualizar un ingreso existente (id=5)
PUT http://localhost:8091/api/ingresos/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxOTQ1MTEsImV4cCI6MTc0ODIzMDUxMX0.Rnf7EUL7PZg4-JIIVsPT-74TQOgjRakWPxQ4zKoKvgo
Content-Type: application/json

{
  "cantidad": "2500,00"
}

### 
### Eliminar un ingreso existente (id=5)
DELETE  http://localhost:8091/api/ingresos/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgxOTQ1MTEsImV4cCI6MTc0ODIzMDUxMX0.Rnf7EUL7PZg4-JIIVsPT-74TQOgjRakWPxQ4zKoKvgo
Content-Type: application/json

### 
### Listar ingresos del usuario autenticado
GET http://localhost:8091/api/ingresos/usuario HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyaTMiLCJpYXQiOjE3NDgxOTY4MjMsImV4cCI6MTc0ODIzMjgyM30.rYFA1B3meRXgtbThH9uKdU_ml-xvyBkw-KMyPlHF6es



### Listar ingresos filtrados por cantidad > 30 y cantidad > 40 ordenados por fecha descendente
GET http://localhost:8091/api/ingresos/filter?filter=cantidad:MAYOR_QUE:0&filter=cantidad:MENOR_QUE:9999&page=1&size=5&sort=fecha,desc&sort=fecha,desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgyODQ1NzYsImV4cCI6MTc0ODMyMDU3Nn0.pUXxgF8SjrehEA2do0RuiVnjXGDSKYZMZZxXTeY4KtY

### Listar ingresos paginados sin filtro

GET http://localhost:8091/api/ingresos/filter?&page=0&size=10&sort=fecha,desc&page=0&size=10&sort=fecha,desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDgyODQ1NzYsImV4cCI6MTc0ODMyMDU3Nn0.pUXxgF8SjrehEA2do0RuiVnjXGDSKYZMZZxXTeY4KtY
