###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "hrisi2",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristiyantg2@gmail.com",
    "password": "Hrisi231104!"
}
###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "hrisi3",
    "nombre": "hristsiyan\nTrayanov",
    "email": "hristiyantg@gmail.com",
    "password": "Hrisi231104!"
}
###
## nuevo correcto
POST http://localhost:8091/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "sofia2",
    "nombre": "sofia\nTrayanova",
    "email": "sofiatg@gmail.com",
    "password": "Sofia230512!"
}
###
## login ok PERMISOS ROLE_ADMIN
POST http://localhost:8091/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "hrisi2",
    "password": "Hrisi231104!"
}
###
## login ok PERMISOS ROLE_USER
POST http://localhost:8091/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "sofia2",
    "password": "Sofia230512!"
}
###
## login ok PERMISOS ROLE_USER
POST http://localhost:8091/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "hrisi3",
    "password": "Hrisi231104!"
}
###
## Crear gasto (asegúrate de usar enums válidos en tipoGasto y subtipo)
POST http://localhost:8091/api/gastos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyODU3ODYsImV4cCI6MTc0NjMyMTc4Nn0.ibShRouPt8h4aki0SrOGXwGgVzgkhhBj2Sddf5dLrng

{
  "usuario": { "id": 1 },
  "grupo": { "id": 1 },
  "tipoGasto": "LUJO",
  "subtipo": "ESTETICA",
  "cantidad": "42,50",
  "fecha": "2025-04-06"
}
###
## Obtener gasto por ID
GET http://localhost:8091/api/gastos/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDUyNTc1MTgsImV4cCI6MTc0NTI5MzUxOH0.68KBlr8CwrklAz-6ftojIvWWYMYrv5BSYQj53XZ216A

###
## Actualizar gasto
PUT http://localhost:8091/api/gastos/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyNzUzNTAsImV4cCI6MTc0NjMxMTM1MH0.qm4iOC3oo0SGPVG9ZFa2frhPkDubhWyHo0TvG7aOmqM

{
  "usuario": { "id": 1 },
  "grupo": { "id": 1 },
  "tipoGasto": "SUPERVIVENCIA",
  "subtipo": "COMIDA",
  "cantidad": 75.00,
  "fecha": "2025-04-07"
}
###
## Eliminar gasto
DELETE http://localhost:8091/api/gastos/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDUzNDI2NTcsImV4cCI6MTc0NTM3ODY1N30.rVvwNwyObe9AjRAtI0XQbxgcGdvigEZalVD4TdDmw4g

###
## Actualizar gasto con id 3
PUT http://localhost:8091/api/gastos/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyODY5MTAsImV4cCI6MTc0NjMyMjkxMH0.wd-Ah-9kkgvFEpDsibVIcpAX8Ef5tCqm_FWE0kT4cnI

{
  "tipoGasto": "LUJO",
  "subtipo": "VIAJES",
  "cantidad": "123,45",
  "fecha": "2025-05-02"
}


###
## Crear grupo familiar (el usuario será el administrador automáticamente si así lo configuraste)
POST http://localhost:8091/api/grupos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyMjA5MDYsImV4cCI6MTc0NjI1NjkwNn0.1iqXFNV6r6LuBMNbNGS58rSALoqLhRDATAxH5N0LRCo

{
  "nombre": "Familia Trayanov2"
}
###
## Obtener grupo por ID
GET http://localhost:8091/api/grupos/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDU0MjkyMDIsImV4cCI6MTc0NTQ2NTIwMn0.h1ap4ND-a2VFq_RcCl0MCPbXNciutXmEdQcbMsSXhlo

###
## Actualizar grupo (solo el administrador puede)
PUT http://localhost:8091/api/grupos/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDUzNDI2NTcsImV4cCI6MTc0NTM3ODY1N30.rVvwNwyObe9AjRAtI0XQbxgcGdvigEZalVD4TdDmw4g

{
  "nombre": "Familia Trayanov Actualizado"
}
###
## Eliminar grupo
DELETE http://localhost:8091/api/grupos/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDUyNTc1MTgsImV4cCI6MTc0NTI5MzUxOH0.68KBlr8CwrklAz-6ftojIvWWYMYrv5BSYQj53XZ216A



###
## Crear mensaje
POST http://localhost:8091/api/mensajes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDUzNDY0MzcsImV4cCI6MTc0NTM4MjQzN30.bZ14JlgtXbR8VCeepiFHO9qjNNV24nUQAdVB8jFu8_8

{
  "emisor": { "id": 1 },
  "receptor": { "id": 2 },
  "grupo": { "id": 1 },
  "contenido": "Hola, este es un mensaje de prueba",
  "fecha": "2025-04-06T18:00:00",
  "tipo": "PRIVADO"
}
###
## Obtener mensaje por ID
GET http://localhost:8091/api/mensajes/1 HTTP/1.1
Authorization: Bearer {{TOKEN}}

###
## Actualizar mensaje
PUT http://localhost:8091/api/mensajes/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "emisor": { "id": 1 },
  "receptor": { "id": 2 },
  "grupo": { "id": 1 },
  "contenido": "Mensaje editado",
  "fecha": "2025-04-06T18:30:00",
  "tipo": "PRIVADO"
}
###
## Sumar gastos de luju espectaculos
GET http://localhost:8091/api/gastos/suma-gastos?tipoGasto=LUJO&subtipo=ESPECTACULOS
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyODQyMjIsImV4cCI6MTc0NjMyMDIyMn0.cBdXM4tbrULQlOZSoyiF9-OqvL0vJmbGV3hiTP_JM5E

###
## sumar gastos de tipo lujo
GET http://localhost:8091/api/gastos/suma-gastos?tipoGasto=LUJO
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyODQyMjIsImV4cCI6MTc0NjMyMDIyMn0.cBdXM4tbrULQlOZSoyiF9-OqvL0vJmbGV3hiTP_JM5E

###
## Eliminar mensaje
DELETE http://localhost:8091/api/mensajes/1 HTTP/1.1
Authorization: Bearer {{TOKEN}}

###
### Crear una invitación para un usuario con nickname "sofia2" al grupo 1
POST http://localhost:8091/api/invitaciones HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYyNzUyMjcsImV4cCI6MTc0NjMxMTIyN30.WK4SOACXZgqLAt-nA4G0W2nfTxJ3H4SivtjYkYH2sfo

{
  "nickname": "hrisi3",
  "grupoId": 1
}

###
### Obtener invitaciones del grupo con ID 1
GET http://localhost:8091/api/invitaciones/grupo/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDU0Mzg1ODAsImV4cCI6MTc0NTQ3NDU4MH0.RKGTRyu1PMudULyTh0hPA4RaxeqfWuoABXhuPgi5fQ8

###
### Marcar invitación con ID 5 como aceptada
PUT http://localhost:8091/api/invitaciones/1/estado?nuevoEstado=ACEPTADA HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTMiLCJpYXQiOjE3NDYyNzUyNDYsImV4cCI6MTc0NjMxMTI0Nn0.6q8ru_VTh_d82IZeOIMVbvxu2N-dhyLWH7dhQHNaHJQ

###
### Obtener todas las invitaciones dirigidas al usuario autenticado

GET http://localhost:8091/api/invitaciones/usuario HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDU5NTE4OTUsImV4cCI6MTc0NTk4Nzg5NX0.w0qqvfChYLeCoT-pqvhfEe-MZOh8GBfAS01nNZgSGUA


###
### Asignar el rol de padre a un usuario del grupo (solo el admin puede hacerlo)Marcar invitación con ID 5 como aceptada
PUT http://localhost:8091/api/invitaciones/asignar-rol?nicknameDestino=sofia2&rol=padre HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDU0Mzg1ODAsImV4cCI6MTc0NTQ3NDU4MH0.RKGTRyu1PMudULyTh0hPA4RaxeqfWuoABXhuPgi5fQ8

###
### ARechazar una invitacion
PUT http://localhost:8091/api/invitaciones/1/estado?nuevoEstado=RECHAZADA HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDU5NTE4OTUsImV4cCI6MTc0NTk4Nzg5NX0.w0qqvfChYLeCoT-pqvhfEe-MZOh8GBfAS01nNZgSGUA
###
### Abandonar el grupo familiar actual (el usuario abandona su grupo)
DELETE http://localhost:8091/api/grupos/abandonar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDU5NTM4NDQsImV4cCI6MTc0NTk4OTg0NH0.X_1RrolfqQI-IGrZ0VbiIPvZh_siCR4RtJPsVYXhZgg

###
### Expulsar al usuario "sofia2" del grupo familiar con ID 1
PUT http://localhost:8091/api/grupos/1/eliminar-usuario/sofia2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDU5NTQxMTMsImV4cCI6MTc0NTk5MDExM30.P25IIYYlDHXEV1QkGWzJV5XEBy0NBZXPejXQxISQ7MA
Content-Type: application/json
###
### Actualizar mis propios datos (nickname viejo en la URL)
PUT http://localhost:8091/api/usuarios/sofia3/actualizar HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTMiLCJpYXQiOjE3NDU5NjM3NTEsImV4cCI6MTc0NTk5OTc1MX0.pA4E4yBLN8eXfICucvDzCXoHMNmlMx5aqzy9b5pKJLE

{
  "nombre": "Sofia Georgi",
  "nickname": "sofia3",
  "email": "nuevo@email.com",
  "password": "NuevaPa",
  "password2": "NuevaPa"
}
###
### Obtener perfil del usuario autenticado
GET http://localhost:8091/api/usuarios/perfil HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb2ZpYTIiLCJpYXQiOjE3NDU5NjAwNjIsImV4cCI6MTc0NTk5NjA2Mn0.oDJI4G-b5yaz8dskACQoPzePJQhlgHe21M7kgy1GVuI



### Obtener todos los usuarios (paginados básicos)
###
GET http://localhost:8091/api/usuarios/usuarios?page=0&size=3&sort=id,asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYxMjQ5OTMsImV4cCI6MTc0NjE2MDk5M30.6JqKWD5LquMIeMMdam8pjQWenY-3jAKC2BolL6-A0N0

###Obtener todos los usuarios paginados
###
GET http://localhost:8091/api/usuarios/v1/usuarios?page=0&size=3&sortField=id&sortDirection=asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYxMjgwMTksImV4cCI6MTc0NjE2NDAxOX0.017jiTjMFxOA2sH3dSriUBpS_ZbmBI2ISzJrAxfQB3I

###Obtener los usuarios mediante busqueda
###
POST http://localhost:8091/api/usuarios/v1/usuarios/x HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocmlzaTIiLCJpYXQiOjE3NDYxMjc0ODEsImV4cCI6MTc0NjE2MzQ4MX0.0IuMAOw6sVz7edeMYXlXv3bnJUrEMEJivQy8w0rI81I

{
  "pagina": 0,
  "size": 3,
  "sort": ["id,asc"],
  "listaFiltros": [
    {
      "campo": "nombre",
      "operador": "contiene",
      "valor": "hris"
    }
  ]
}


