package proyect.proyectefinal.model.enums;



public enum SubtipoGasto {
    // SUPERVIVENCIA
    AGUA(1), BASURAS(2), COMIDA(3), COMUNIDAD(4), FARMACIA(5), GAS(6), GASOIL(7), GIMNASIO(8), HIJOS(9), HIPOTECA(10),
    IBI(11), LUZ(12), MANT_COCHE(13), MUTUA(14), ROPA_IMPRESCINDIBLE(15), SALUD(16), SEGURO_HOGAR(17),
    SEGURO_VIDA(18), COCHERA(19), CASA_APARATOS(20), DOCUMENTOS(21),

    // LUJO
    ESPECTACULOS(22), ESTETICA(23), MAQUILLAJE(24), PARKING(25), REGALOS(26), RESTAURANTES(27),
    ROPA_COMPLEMENTOS(28), SUBSCRIPCIONES_OCIO(29), VIAJES(30), SALIDAS_OCIO(31), TELEFONO_INTERNET(32), LOTERIA(33),
    FALLA(34), LUJO_NIÑOS(35),

    // EDUCACION
    CURSOS(36), LIBROS(37), MASTERS(38), SUBSCRIPCIONES_EDU(39),PROGRAMAS(40),

    // AHORRO
    BANKINTER(41),  TRADE_REPUBLIC(42), CAIXABANK(43), SABADELL(44),MY_INVESTOR(45),//Aqui debe haber un segundo MYINVESTOR

    // INVERSION
    HAUSERA(46), IB(47), MYINVESTOR(48), BINANCE(49);



    private final int id;
    SubtipoGasto(int id){
        this.id = id;
    }
}
