package proyect.proyectefinal.model.enums;



public enum SubtipoGasto {
    // SUPERVIVENCIA
    AGUA, BASURAS, COMIDA, COMUNIDAD, FARMACIA, GAS, GASOIL, GIMNASIO, HIJOS, HIPOTECA,
    IBI, LUZ, MANT_COCHE, MUTUA, ROPA_IMPRESCINDIBLE, SALUD, SEGURO_HOGAR,
    SEGURO_VIDA, COCHERA, CASA_APARATOS, DOCUMENTOS,

    // LUJO
    ESPECTACULOS, ESTETICA, MAQUILLAJE, PARKING, REGALOS, RESTAURANTES,
    ROPA_COMPLEMENTOS, SUBS_OCIO, VIAJES, SALIDAS_OCIO, TELEFONO_INTERNET, LOTERIA,
    FALLA, LUJO_NIÑOS,

    // EDUCACION
    CURSOS, LIBROS, MASTERS, SUBSCRIPCIONES_EDU, PROGRAMAS,

    // AHORRO
    BANKINTER,  TRADE_REPUBLIC, CAIXABANK, SABADELL,//Aqui debe haber un segundo MYINVESTOR

    // INVERSION
    HAUSERA, IB, MYINVESTOR, BINANCE
}
